# Generated by Django 5.0.7 on 2024-08-06 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient_id', models.PositiveIntegerField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
            options={
                'verbose_name': 'doctor admission',
                'verbose_name_plural': 'doctor admissions',
                'db_table': 'doctor_admission',
            },
        ),
    ]
